package com.spaceconquest.engine.demographics;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * Represents a single-education, single-profession demographic fragment of citizens.
 * Follows the weighted cohort model where 1.0 standard cohort unit corresponds to 100,000 citizens,
 * while partial fragments operate at continuous fractional efficiency.
 *
 * @param id           unique cohort identifier
 * @param raceId       species or race identifier
 * @param professionId identifier of the single profession/education profile
 * @param ageBracket   chronological age or demographic age bracket. This will likely be an average value as one cohort per age group will be too complex.
 * @param headcount    exact number of individuals in this cohort fragment
 */
public record CitizenCohort(
        @JsonProperty("id") String id,
        @JsonProperty("raceId") String raceId,
        @JsonProperty("professionId") String professionId,
        @JsonProperty("ageBracket") int ageBracket,
        @JsonProperty("headcount") long headcount
) {
    public static final long STANDARD_COHORT_SIZE = 100_000L;
    public static final long MIN_COHORT_SIZE = 1L;

    public CitizenCohort {
        Objects.requireNonNull(raceId, "raceId cannot be null");
        Objects.requireNonNull(professionId, "professionId cannot be null");
        if (id == null || id.isBlank()) {
            id = raceId + "_" + professionId + "_" + ageBracket;
        }
        if (headcount < 0) {
            headcount = 0;
        }
    }

    public CitizenCohort(String raceId, String professionId, int ageBracket, long headcount) {
        this(raceId + "_" + professionId + "_" + ageBracket, raceId, professionId, ageBracket, headcount);
    }

    /**
     * Converts the absolute headcount into normalized standard cohort units (1.0 = 100,000 citizens).
     *
     * @return cohort units as a decimal fraction
     */
    public double toCohortUnits() {
        return (double) headcount / (double) STANDARD_COHORT_SIZE;
    }

    /**
     * Calculates fractional staffing efficiency against a required absolute headcount.
     *
     * @param requiredHeadcount required personnel headcount
     * @return efficiency factor clamped between 0.0 and 1.0
     */
    public double calculateStaffingEfficiency(long requiredHeadcount) {
        if (requiredHeadcount <= 0) {
            return 1.0;
        }
        return Math.min(1.0, (double) headcount / (double) requiredHeadcount);
    }

    /**
     * Calculates fractional staffing efficiency against a required standard cohort quota.
     *
     * @param requiredCohortUnits required cohort units (e.g. 0.02 for 2,000 personnel)
     * @return efficiency factor clamped between 0.0 and 1.0
     */
    public double calculateWorkforceEfficiency(double requiredCohortUnits) {
        if (requiredCohortUnits <= 0.0) {
            return 1.0;
        }
        return Math.min(1.0, toCohortUnits() / requiredCohortUnits);
    }

    /**
     * Calculates weighted operational output scaling linearly with cohort fraction.
     *
     * @param baseOutput nominal output when fully staffed
     * @param requiredCohortUnits required cohort units
     * @return effective output
     */
    public double calculateWeightedOutput(double baseOutput, double requiredCohortUnits) {
        return baseOutput * calculateWorkforceEfficiency(requiredCohortUnits);
    }

    /**
     * Calculates the gross wage bill for this cohort fragment for a turn.
     *
     * @param baseWageCredits base compensation in credits per citizen
     * @return total credits payable
     */
    public double calculateWageBill(double baseWageCredits) {
        return (double) headcount * Math.max(0.0, baseWageCredits);
    }

    /**
     * Calculates the income tax generated by this cohort fragment for a turn.
     *
     * @param baseWageCredits base compensation in credits per citizen
     * @param systemTaxRate income tax rate (0.0 to 1.0)
     * @return total income tax credits collected
     */
    public double calculateIncomeTax(double baseWageCredits, double systemTaxRate) {
        return calculateWageBill(baseWageCredits) * Math.max(0.0, systemTaxRate);
    }

    /**
     * Returns a new cohort fragment with the specified headcount.
     */
    public CitizenCohort withHeadcount(long newHeadcount) {
        return new CitizenCohort(id, raceId, professionId, ageBracket, newHeadcount);
    }

    /**
     * Returns a new cohort fragment with the specified age bracket.
     */
    public CitizenCohort withAgeBracket(int newAgeBracket) {
        return new CitizenCohort(raceId + "_" + professionId + "_" + newAgeBracket, raceId, professionId, newAgeBracket, headcount);
    }

    /**
     * Checks if this cohort fragment can be merged with another (matching species, profession and age).
     */
    public boolean canMerge(CitizenCohort other) {
        if (other == null) {
            return false;
        }
        return Objects.equals(raceId, other.raceId)
                && Objects.equals(professionId, other.professionId)
                && ageBracket == other.ageBracket;
    }

    /**
     * Merges another compatible cohort fragment into this one.
     */
    public CitizenCohort merge(CitizenCohort other) {
        if (!canMerge(other)) {
            throw new IllegalArgumentException("Cannot merge incompatible cohorts: " + this + " vs " + other);
        }
        return new CitizenCohort(id, raceId, professionId, ageBracket, headcount + other.headcount);
    }

    /**
     * Checks if this cohort is past retirement age.
     */
    public boolean isRetired(int retirementAge) {
        return ageBracket >= retirementAge;
    }
}
